#!/bin/bash
#bash gitps.sh site user
if [ -z $1 ] ; then
echo «Do not set your domain name.»
exit 1 ; fi
if [ -z $2 ] ; then
username='im'
echo «Do not set your user name.» ; fi

#git prepare
ipsrv='192.168.0.1'
sitename=$1
cd /home/$username/public_html/$1
git init
git config receive.denyCurrentBranch ignore

touch .git/hooks/post-receive
cat << EOF > .git/hooks/post-receive
#!/bin/sh
cd ..
GIT_DIR='.git'
git reset --hard
EOF
chmod +x .git/hooks/post-receive

touch readme.txt
cat << EOF >readme.txt
firstcommit
EOF

git add . && git commit -m "commit subject about change"
echo "git clone ssh://${username}@${ipsrv}/~/public_html/${sitename}/.git ."
cd /home/$username/public_html
